CREATE TABLE [dbo].[Pet]
(
	[PetID] INT NOT NULL,
	[OwnerID] INT NOT NULL,
	[Name] NVARCHAR(50),
	[Type] NVARCHAR(50),
	CONSTRAINT PK_PET PRIMARY KEY (PetID),
	CONSTRAINT FK_OWNER FOREIGN KEY (OwnerID) REFERENCES [Owner] (OwnerID),
	CONSTRAINT U_PET UNIQUE (PetID, OwnerID)
)
