CREATE TABLE [dbo].[Treatment]
(
	[ProcedureID] INT NOT NULL,
	[PetID] INT NOT NULL,
	[Date] DATE NOT NULL,
	[Notes] NVARCHAR(50) NOT NULL,
	[Price] MONEY NOT NULL,
	CONSTRAINT PK_TREATMENT PRIMARY KEY (ProcedureID, PetID, [Date]),
	CONSTRAINT PK_PROCEDURE FOREIGN KEY (ProcedureID) REFERENCES [Procedure] (ProcedureID),
	CONSTRAINT FK_PET FOREIGN KEY (PetID) REFERENCES Pet(PetID),
)
